name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # GitVersioning needs deep clone

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Set up NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore
      run: dotnet restore Mono.TextTemplating.sln -p:Configuration=Release -m

    - name: Build
      run: dotnet build Mono.TextTemplating.sln -p:Configuration=Release -m --no-restore

    - name: Test (Windows)
      if: startsWith (matrix.os, 'windows')
      run: dotnet test

    - name: Test (Linux/Mac)
      if: startsWith (matrix.os, 'windows') == false
      run: \
        nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner
        mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Mono.TextTemplating.Tests/bin/Release/net472/Mono.TextTemplating.Tests.dll

    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: packages/Release

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: packages
          name: packages

      - name: Set up NuGet
        uses: nuget/setup-nuget@v1

      - name: Publish to GPR
        run: \
          nuget push "packages\**\*.nupkg" \
          --api-key ${{ secrets.GITHUB_TOKEN }}
          -Source https://nuget.pkg.github.com/${{ github.repository_owner }}
          -SkipDuplicate

      - name: Publish to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: \
          nuget push "packages\**\*.nupkg" \
          --api-key ${{ secrets.NUGETAPIKEY }}
          -SkipDuplicate